### PR TITLE
Try building on Windows

### PR DESCRIPTION
**Pull request by xhochy**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xhochy** [comment]
Needs https://github.com/conda-forge/safeint-feedstock/pull/4 and https://github.com/conda-forge/optional-lite-feedstock/pull/3

**Comment by xhochy** [comment]
This needs a statically linked libprotobuf on Windows.

**Comment by jamesmyatt** [comment]
Closes #31

**Comment by cbourjau** [comment]
Closed with #56

**Pull request closed without merging**
