### PR TITLE
Test CUDA compilation on Windows

### PR DESCRIPTION
**Pull request by traversaro**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
CUDA 12 error:
~~~
(%BUILD_PREFIX%) %SRC_DIR%>python tools/ci_build/build.py     --compile_no_warning_as_error     --build_dir build-ci     --cmake_extra_defines EIGEN_MPL2_ONLY=ON "onnxruntime_USE_COREML=OFF" "onnxruntime_BUILD_SHARED_LIB=ON" "onnxruntime_BUILD_UNIT_TESTS=ON" CMAKE_PREFIX_PATH=%PREFIX%\Library CMAKE_INSTALL_PREFIX=%PREFIX%\Library CMAKE_DISABLE_FIND_PACKAGE_Protobuf=ON CMAKE_CUDA_ARCHITECTURES=all     --cmake_generator Ninja     --build_wheel     --config Release     --update     --build     --skip_submodule_sync     --use_cuda --cudnn_home %PREFIX%\Library 
2024-05-08 09:44:58,414 build [DEBUG] - Command line arguments:
  --compile_no_warning_as_error --build_dir build-ci --cmake_extra_defines EIGEN_MPL2_ONLY=ON onnxruntime_USE_COREML=OFF onnxruntime_BUILD_SHARED_LIB=ON onnxruntime_BUILD_UNIT_TESTS=ON 'CMAKE_PREFIX_PATH=D:\bld\onnxruntime_1715161041292\_h_env\Library' 'CMAKE_INSTALL_PREFIX=D:\bld\onnxruntime_1715161041292\_h_env\Library' CMAKE_DISABLE_FIND_PACKAGE_Protobuf=ON CMAKE_CUDA_ARCHITECTURES=all --cmake_generator Ninja --build_wheel --config Release --update --build --skip_submodule_sync --use_cuda --cudnn_home 'D:\bld\onnxruntime_1715161041292\_h_env\Library'
Namespace(build_dir='build-ci', config=['Release'], update=True, build=True, clean=False, parallel=1, nvcc_threads=-1, test=False, skip_tests=False, compile_no_warning_as_error=True, enable_nvtx_profile=False, enable_memory_profile=False, enable_training=False, enable_training_apis=False, enable_training_ops=False, enable_nccl=False, mpi_home=None, nccl_home=None, use_mpi=False, enable_onnx_tests=False, path_to_protoc_exe=None, fuzz_testing=False, enable_symbolic_shape_infer_tests=False, gen_doc=None, gen_api_doc=False, use_cuda=True, cuda_version=None, cuda_home=None, cudnn_home='D:\\bld\\onnxruntime_1715161041292\\_h_env\\Library', enable_cuda_line_info=False, enable_cuda_nhwc_ops=False, enable_pybind=False, build_wheel=True, wheel_name_suffix=None, numpy_version=None, skip_keras_test=False, build_csharp=False, build_nuget=False, msbuild_extra_options=None, build_java=False, build_nodejs=False, build_objc=False, build_shared_lib=False, build_apple_framework=False, cmake_extra_defines=[['EIGEN_MPL2_ONLY=ON', 'onnxruntime_USE_COREML=OFF', 'onnxruntime_BUILD_SHARED_LIB=ON', 'onnxruntime_BUILD_UNIT_TESTS=ON', 'CMAKE_PREFIX_PATH=D:\\bld\\onnxruntime_1715161041292\\_h_env\\Library', 'CMAKE_INSTALL_PREFIX=D:\\bld\\onnxruntime_1715161041292\\_h_env\\Library', 'CMAKE_DISABLE_FIND_PACKAGE_Protobuf=ON', 'CMAKE_CUDA_ARCHITECTURES=all']], target=None, x86=False, arm=False, arm64=False, arm64ec=False, buildasx=False, msvc_toolset=None, windows_sdk_version=None, android=False, android_abi='arm64-v8a', android_api=27, android_sdk_path='C:\\Android\\android-sdk', android_ndk_path='C:\\Android\\android-sdk\\ndk\\25.2.9519653', android_cpp_shared=False, android_run_emulator=False, use_gdk=False, gdk_edition='.', gdk_platform='Scarlett', ios=False, apple_sysroot='', ios_toolchain_file='', xcode_code_signing_team_id='', xcode_code_signing_identity='', cmake_generator='Ninja', osx_arch='x86_64', apple_deploy_target=None, enable_address_sanitizer=False, enable_qspectre=False, disable_memleak_checker=False, build_wasm=False, build_wasm_static_lib=False, emsdk_version='3.1.51', enable_wasm_simd=False, enable_wasm_threads=False, disable_wasm_exception_catching=False, enable_wasm_api_exception_catching=False, enable_wasm_exception_throwing_override=True, wasm_run_tests_in_browser=False, enable_wasm_profiling=False, enable_wasm_debug_info=False, wasm_malloc=None, emscripten_settings=None, use_extensions=False, extensions_overridden_path=None, cmake_path='cmake', ctest_path='ctest', skip_submodule_sync=True, use_mimalloc=False, use_dnnl=False, dnnl_gpu_runtime='', dnnl_opencl_root='', use_openvino=None, dnnl_aarch64_runtime='', dnnl_acl_root='', use_coreml=False, use_webnn=False, use_snpe=False, snpe_root=None, use_nnapi=False, nnapi_min_api=None, use_jsep=False, use_qnn=False, qnn_home=None, use_rknpu=False, use_preinstalled_eigen=False, eigen_path=None, enable_msinternal=False, llvm_path=None, use_vitisai=False, use_tvm=False, tvm_cuda_runtime=False, use_tvm_hash=False, use_tensorrt=False, use_tensorrt_builtin_parser=True, use_tensorrt_oss_parser=False, tensorrt_home=None, test_all_timeout='10800', use_migraphx=False, migraphx_home=None, use_full_protobuf=False, llvm_config='', skip_onnx_tests=False, skip_winml_tests=False, skip_nodejs_tests=False, enable_msvc_static_runtime=False, enable_language_interop_ops=False, use_dml=False, dml_path='', use_winml=False, winml_root_namespace_override=None, dml_external_project=False, use_telemetry=False, enable_wcos=False, enable_lto=False, enable_transformers_tool_test=False, use_acl=None, acl_home=None, acl_libs=None, use_armnn=False, armnn_relu=False, armnn_bn=False, armnn_home=None, armnn_libs=None, build_micro_benchmarks=False, minimal_build=None, include_ops_by_config=None, enable_reduced_operator_type_support=False, disable_contrib_ops=False, disable_ml_ops=False, disable_rtti=False, disable_types=[], disable_exceptions=False, rocm_version=None, use_rocm=False, rocm_home=None, code_coverage=False, enable_lazy_tensor=False, ms_experimental=False, enable_external_custom_op_schemas=False, external_graph_transformer_path=None, enable_cuda_profiling=False, use_cann=False, cann_home=None, enable_rocm_profiling=False, use_xnnpack=False, use_azure=False, use_cache=False, use_triton_kernel=False, use_lock_free_queue=False)
2024-05-08 09:44:58,508 build [ERROR] - cuda_home and cudnn_home paths must be specified and valid.
cuda_home='None' valid=False. cudnn_home='D:\bld\onnxruntime_1715161041292\_h_env\Library' valid=True
~~~

Usual CUDA 12 migration problem.

CUDA 11.8 error:
~~~
-- Found PythonInterp: D:/bld/onnxruntime_1715162047283/_h_env/python.exe (found version "3.11.9")
Generated: D:/bld/onnxruntime_1715162047283/work/build-ci/Release/_deps/onnx-build/onnx/onnx-ml.proto
Generated: D:/bld/onnxruntime_1715162047283/work/build-ci/Release/_deps/onnx-build/onnx/onnx-operators-ml.proto
Generated: D:/bld/onnxruntime_1715162047283/work/build-ci/Release/_deps/onnx-build/onnx/onnx-data.proto
  File "D:\bld\onnxruntime_1715162047283\work\tools\ci_build\build.py", line 1607, in generate_build_tree
    run_subprocess(
  File "D:\bld\onnxruntime_1715162047283\work\tools\ci_build\build.py", line 839, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\bld\onnxruntime_1715162047283\work\tools\python\util\run.py", line 49, in run
    completed_process = subprocess.run(
                        ^^^^^^^^^^^^^^^
  File "D:\bld\onnxruntime_1715162047283\_h_env\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['D:\\bld\\onnxruntime_1715162047283\\_build_env\\Library\\bin\\cmake.EXE', 'D:\\bld\\onnxruntime_1715162047283\\work\\cmake', '--compile-no-warning-as-error', '-Donnxruntime_RUN_ONNX_TESTS=OFF', '-Donnxruntime_GENERATE_TEST_REPORTS=ON', '-DPython_EXECUTABLE=D:\\bld\\onnxruntime_1715162047283\\_h_env\\python.exe', '-DPYTHON_EXECUTABLE=D:\\bld\\onnxruntime_1715162047283\\_h_env\\python.exe', '-Donnxruntime_USE_MIMALLOC=OFF', '-Donnxruntime_ENABLE_PYTHON=ON', '-Donnxruntime_BUILD_CSHARP=OFF', '-Donnxruntime_BUILD_JAVA=OFF', '-Donnxruntime_BUILD_NODEJS=OFF', '-Donnxruntime_BUILD_OBJC=OFF', '-Donnxruntime_BUILD_SHARED_LIB=OFF', '-Donnxruntime_BUILD_APPLE_FRAMEWORK=OFF', '-Donnxruntime_USE_DNNL=OFF', '-Donnxruntime_USE_NNAPI_BUILTIN=OFF', '-Donnxruntime_USE_RKNPU=OFF', '-Donnxruntime_USE_LLVM=OFF', '-Donnxruntime_ENABLE_MICROSOFT_INTERNAL=OFF', '-Donnxruntime_USE_VITISAI=OFF', '-Donnxruntime_USE_TENSORRT=OFF', '-Donnxruntime_USE_TENSORRT_BUILTIN_PARSER=ON', '-Donnxruntime_USE_TVM=OFF', '-Donnxruntime_TVM_CUDA_RUNTIME=OFF', '-Donnxruntime_TVM_USE_HASH=OFF', '-Donnxruntime_USE_MIGRAPHX=OFF', '-Donnxruntime_DISABLE_CONTRIB_OPS=OFF', '-Donnxruntime_DISABLE_ML_OPS=OFF', '-Donnxruntime_DISABLE_RTTI=OFF', '-Donnxruntime_DISABLE_EXCEPTIONS=OFF', '-Donnxruntime_MINIMAL_BUILD=OFF', '-Donnxruntime_EXTENDED_MINIMAL_BUILD=OFF', '-Donnxruntime_MINIMAL_BUILD_CUSTOM_OPS=OFF', '-Donnxruntime_REDUCED_OPS_BUILD=OFF', '-Donnxruntime_ENABLE_LANGUAGE_INTEROP_OPS=OFF', '-Donnxruntime_USE_DML=OFF', '-Donnxruntime_USE_WINML=OFF', '-Donnxruntime_BUILD_MS_EXPERIMENTAL_OPS=OFF', '-Donnxruntime_USE_TELEMETRY=OFF', '-Donnxruntime_ENABLE_LTO=OFF', '-Donnxruntime_USE_ACL=OFF', '-Donnxruntime_USE_ACL_1902=OFF', '-Donnxruntime_USE_ACL_1905=OFF', '-Donnxruntime_USE_ACL_1908=OFF', '-Donnxruntime_USE_ACL_2002=OFF', '-Donnxruntime_USE_ACL_2308=OFF', '-Donnxruntime_USE_ARMNN=OFF', '-Donnxruntime_ARMNN_RELU_USE_CPU=ON', '-Donnxruntime_ARMNN_BN_USE_CPU=ON', '-Donnxruntime_USE_JSEP=OFF', '-Donnxruntime_ENABLE_NVTX_PROFILE=OFF', '-Donnxruntime_ENABLE_TRAINING=OFF', '-Donnxruntime_ENABLE_TRAINING_OPS=OFF', '-Donnxruntime_ENABLE_TRAINING_APIS=OFF', '-Donnxruntime_ENABLE_CPU_FP16_OPS=OFF', '-Donnxruntime_USE_NCCL=OFF', '-Donnxruntime_BUILD_BENCHMARKS=OFF', '-Donnxruntime_USE_ROCM=OFF', '-DOnnxruntime_GCOV_COVERAGE=OFF', '-Donnxruntime_USE_MPI=OFF', '-Donnxruntime_ENABLE_MEMORY_PROFILE=OFF', '-Donnxruntime_ENABLE_CUDA_LINE_NUMBER_INFO=OFF', '-Donnxruntime_USE_CUDA_NHWC_OPS=OFF', '-Donnxruntime_BUILD_WEBASSEMBLY_STATIC_LIB=OFF', '-Donnxruntime_ENABLE_WEBASSEMBLY_EXCEPTION_CATCHING=ON', '-Donnxruntime_ENABLE_WEBASSEMBLY_API_EXCEPTION_CATCHING=OFF', '-Donnxruntime_ENABLE_WEBASSEMBLY_EXCEPTION_THROWING=ON', '-Donnxruntime_WEBASSEMBLY_RUN_TESTS_IN_BROWSER=OFF', '-Donnxruntime_ENABLE_WEBASSEMBLY_THREADS=OFF', '-Donnxruntime_ENABLE_WEBASSEMBLY_DEBUG_INFO=OFF', '-Donnxruntime_ENABLE_WEBASSEMBLY_PROFILING=OFF', '-Donnxruntime_ENABLE_LAZY_TENSOR=OFF', '-Donnxruntime_ENABLE_EXTERNAL_CUSTOM_OP_SCHEMAS=OFF', '-Donnxruntime_ENABLE_CUDA_PROFILING=OFF', '-Donnxruntime_ENABLE_ROCM_PROFILING=OFF', '-Donnxruntime_USE_XNNPACK=OFF', '-Donnxruntime_USE_WEBNN=OFF', '-Donnxruntime_USE_CANN=OFF', '-Donnxruntime_USE_TRITON_KERNEL=OFF', '-Donnxruntime_DISABLE_FLOAT8_TYPES=OFF', '-Donnxruntime_DISABLE_SPARSE_TENSORS=OFF', '-Donnxruntime_DISABLE_OPTIONAL_TYPE=OFF', '-Donnxruntime_NVCC_THREADS=1', '-DEIGEN_MPL2_ONLY=ON', '-Donnxruntime_USE_COREML=OFF', '-Donnxruntime_BUILD_SHARED_LIB=ON', '-Donnxruntime_BUILD_UNIT_TESTS=ON', '-DCMAKE_PREFIX_PATH=D:\\bld\\onnxruntime_1715162047283\\_h_env\\Library', '-DCMAKE_INSTALL_PREFIX=D:\\bld\\onnxruntime_1715162047283\\_h_env\\Library', '-DCMAKE_DISABLE_FIND_PACKAGE_Protobuf=ON', '-DCMAKE_CUDA_ARCHITECTURES=all', '-DCMAKE_TLS_VERIFY=ON', '-DFETCHCONTENT_QUIET=OFF', '-Donnxruntime_USE_CUDA=ON', '-Donnxruntime_CUDA_HOME=C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.8', '-Donnxruntime_CUDNN_HOME=D:\\bld\\onnxruntime_1715162047283\\_h_env\\Library', '-DONNX_USE_MSVC_STATIC_RUNTIME=OFF', '-Dprotobuf_MSVC_STATIC_RUNTIME=OFF', '-Dgtest_force_shared_crt=ON', '-DCMAKE_MSVC_DEBUG_INFORMATION_FORMAT=ProgramDatabase', '-G', 'Ninja', '-DVERSION_MAJOR_PART=1', '-DVERSION_MINOR_PART=17', '-DVERSION_BUILD_PART=24', '-DVERSION_PRIVATE_PART=0508', '-DVERSION_STRING=1.17.20240508.4.04fd7d6', '-DCMAKE_C_FLAGS=/guard:cf /DWIN32 /D_WINDOWS /MP /DWINAPI_FAMILY=100 /DWINVER=0x0A00 /D_WIN32_WINNT=0x0A00 /DNTDDI_VERSION=0x0A000000 /Qspectre /DONNXRUNTIME_ENABLE_INTEL_METEOR_LAKE_MOBILE_PLATFORM_PERF_PATCH /O2 /Ob2 /DNDEBUG', '-DCMAKE_CXX_FLAGS=/guard:cf /DWIN32 /D_WINDOWS /MP /DWINAPI_FAMILY=100 /DWINVER=0x0A00 /D_WIN32_WINNT=0x0A00 /DNTDDI_VERSION=0x0A000000 /Qspectre /DONNXRUNTIME_ENABLE_INTEL_METEOR_LAKE_MOBILE_PLATFORM_PERF_PATCH /O2 /Ob2 /DNDEBUG /EHsc', '-DCMAKE_CUDA_FLAGS_INIT=/DWIN32 /D_WINDOWS /DWINAPI_FAMILY=100 /DWINVER=0x0A00 /D_WIN32_WINNT=0x0A00 /DNTDDI_VERSION=0x0A000000 /DONNXRUNTIME_ENABLE_INTEL_METEOR_LAKE_MOBILE_PLATFORM_PERF_PATCH /DNDEBUG -Xcompiler=" /guard:cf /MP /Qspectre /O2 /Ob2"', '-DCMAKE_EXE_LINKER_FLAGS_INIT=/profile /DYNAMICBASE', '-DCMAKE_MODULE_LINKER_FLAGS_INIT=/profile /DYNAMICBASE', '-DCMAKE_SHARED_LINKER_FLAGS_INIT=/profile /DYNAMICBASE', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_PREFIX_PATH=build-ci/Release/installed']' returned non-zero exit status 1.
~~~

**Comment by traversaro** [comment]
Based on:
* https://conda-metadata-app.streamlit.app/?q=conda-forge%2Flinux-64%2Fcuda-cudart_linux-64-12.0.107-h59595ed_2.conda
* https://conda-metadata-app.streamlit.app/?q=conda-forge%2Fnoarch%2Fcuda-cudart-dev_win-64-12.4.127-he0c23c2_2.conda

I guess CUDA_HOME can be simply `%LIBRARY_PREFIX%` .

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
Now the builds (also the non-CUDA one) fails with:
~~~
CMake Error at D:/bld/onnxruntime_1715858000512/_build_env/Library/share/cmake-3.29/Modules/CMakeDetermineCCompiler.cmake:49 (message):
  Could not find compiler set in environment variable CC:
-- Configuring incomplete, errors occurred!

  cl.exe.
Call Stack (most recent call first):
  CMakeLists.txt:20 (project)
~~~

this smells like an environment regression, for example in CI images or similar.

**Comment by traversaro** [comment]
Also CUDA 12 fails with:

~~~
  It fails with the following output:

    Change Dir: 'D:/bld/onnxruntime_1716234839539/work/build-ci/Release/CMakeFiles/CMakeScratch/TryCompile-fjxebz'
    
    Run Build Command(s): D:/bld/onnxruntime_1716234839539/_build_env/Library/bin/ninja.exe -v cmTC_dd5bb
    [1/2] D:\bld\onnxruntime_1716234839539\_build_env\Library\bin\nvcc.exe -forward-unknown-to-host-compiler   /DWIN32 /D_WINDOWS /DWINAPI_FAMILY=100 /DWINVER=0x0A00 /D_WIN32_WINNT=0x0A00 /DNTDDI_VERSION=0x0A000000 /DONNXRUNTIME_ENABLE_INTEL_METEOR_LAKE_MOBILE_PLATFORM_PERF_PATCH /DNDEBUG -Xcompiler=" /guard:cf /MP /Qspectre /O2 /Ob2"  -D_WINDOWS -Xcompiler=" /EHsc"  -Xcompiler=" -Ob0 -Od /RTC1" -arch=all -Xcompiler=-MDd -Xcompiler=-Zi -MD -MT CMakeFiles\cmTC_dd5bb.dir\main.cu.obj -MF CMakeFiles\cmTC_dd5bb.dir\main.cu.obj.d -x cu -c D:\bld\onnxruntime_1716234839539\work\build-ci\Release\CMakeFiles\CMakeScratch\TryCompile-fjxebz\main.cu -o CMakeFiles\cmTC_dd5bb.dir\main.cu.obj -Xcompiler=-FdCMakeFiles\cmTC_dd5bb.dir\,-FS
    FAILED: CMakeFiles/cmTC_dd5bb.dir/main.cu.obj 
    D:\bld\onnxruntime_1716234839539\_build_env\Library\bin\nvcc.exe -forward-unknown-to-host-compiler   /DWIN32 /D_WINDOWS /DWINAPI_FAMILY=100 /DWINVER=0x0A00 /D_WIN32_WINNT=0x0A00 /DNTDDI_VERSION=0x0A000000 /DONNXRUNTIME_ENABLE_INTEL_METEOR_LAKE_MOBILE_PLATFORM_PERF_PATCH /DNDEBUG -Xcompiler=" /guard:cf /MP /Qspectre /O2 /Ob2"  -D_WINDOWS -Xcompiler=" /EHsc"  -Xcompiler=" -Ob0 -Od /RTC1" -arch=all -Xcompiler=-MDd -Xcompiler=-Zi -MD -MT CMakeFiles\cmTC_dd5bb.dir\main.cu.obj -MF CMakeFiles\cmTC_dd5bb.dir\main.cu.obj.d -x cu -c D:\bld\onnxruntime_1716234839539\work\build-ci\Release\CMakeFiles\CMakeScratch\TryCompile-fjxebz\main.cu -o CMakeFiles\cmTC_dd5bb.dir\main.cu.obj -Xcompiler=-FdCMakeFiles\cmTC_dd5bb.dir\,-FS
    nvcc fatal   : A single input file is required for a non-link phase when an outputfile is specified

    ninja: build stopped: subcommand failed.
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:705 (enable_language)

~~~

**Comment by traversaro** [comment]
Probably there is some argument that should not be there, that is then interpreter by the compiler as an input file, generating the error (see https://forums.developer.nvidia.com/t/solved-nvcc-fatal-a-single-input-file-is-required-for-a-non-link-phase-when-an-outputfile-is-s/37807 for a similar error). I can easily check this locally to understand which command is wrong.

**Comment by traversaro** [comment]
> Now the builds (also the non-CUDA one) fails with:
> 
> ```
> CMake Error at D:/bld/onnxruntime_1715858000512/_build_env/Library/share/cmake-3.29/Modules/CMakeDetermineCCompiler.cmake:49 (message):
>   Could not find compiler set in environment variable CC:
> -- Configuring incomplete, errors occurred!
> 
>   cl.exe.
> Call Stack (most recent call first):
>   CMakeLists.txt:20 (project)
> ```
> 
> this smells like an environment regression, for example in CI images or similar.

By the way, this was fixed by https://github.com/conda-forge/vc-feedstock/pull/76, thanks @mgovers!

**Comment by traversaro** [comment]
The problem in:

~~~
    [1/2] D:\bld\onnxruntime_1716234839539\_build_env\Library\bin\nvcc.exe -forward-unknown-to-host-compiler   /DWIN32 /D_WINDOWS /DWINAPI_FAMILY=100 /DWINVER=0x0A00 /D_WIN32_WINNT=0x0A00 /DNTDDI_VERSION=0x0A000000 /DONNXRUNTIME_ENABLE_INTEL_METEOR_LAKE_MOBILE_PLATFORM_PERF_PATCH /DNDEBUG -Xcompiler=" /guard:cf /MP /Qspectre /O2 /Ob2"  -D_WINDOWS -Xcompiler=" /EHsc"  -Xcompiler=" -Ob0 -Od /RTC1" -arch=all -Xcompiler=-MDd -Xcompiler=-Zi -MD -MT CMakeFiles\cmTC_dd5bb.dir\main.cu.obj -MF CMakeFiles\cmTC_dd5bb.dir\main.cu.obj.d -x cu -c D:\bld\onnxruntime_1716234839539\work\build-ci\Release\CMakeFiles\CMakeScratch\TryCompile-fjxebz\main.cu -o CMakeFiles\cmTC_dd5bb.dir\main.cu.obj -Xcompiler=-FdCMakeFiles\cmTC_dd5bb.dir\,-FS
~~~

Are the `/DWIN32 /D_WINDOWS /DWINAPI_FAMILY=100 /DWINVER=0x0A00 /D_WIN32_WINNT=0x0A00 /DNTDDI_VERSION=0x0A000000 /DONNXRUNTIME_ENABLE_INTEL_METEOR_LAKE_MOBILE_PLATFORM_PERF_PATCH /DNDEBUG` options, manually converting them to `-DWIN32 -D_WINDOWS -DWINAPI_FAMILY=100 -DWINVER=0x0A00 -D_WIN32_WINNT=0x0A00 -DNTDDI_VERSION=0x0A000000 -DONNXRUNTIME_ENABLE_INTEL_METEOR_LAKE_MOBILE_PLATFORM_PERF_PATCH -DNDEBUG` everything compiles fine (actually, at least the error is different).

**Comment by traversaro** [comment]
> The problem in:
> 
> ```
>     [1/2] D:\bld\onnxruntime_1716234839539\_build_env\Library\bin\nvcc.exe -forward-unknown-to-host-compiler   /DWIN32 /D_WINDOWS /DWINAPI_FAMILY=100 /DWINVER=0x0A00 /D_WIN32_WINNT=0x0A00 /DNTDDI_VERSION=0x0A000000 /DONNXRUNTIME_ENABLE_INTEL_METEOR_LAKE_MOBILE_PLATFORM_PERF_PATCH /DNDEBUG -Xcompiler=" /guard:cf /MP /Qspectre /O2 /Ob2"  -D_WINDOWS -Xcompiler=" /EHsc"  -Xcompiler=" -Ob0 -Od /RTC1" -arch=all -Xcompiler=-MDd -Xcompiler=-Zi -MD -MT CMakeFiles\cmTC_dd5bb.dir\main.cu.obj -MF CMakeFiles\cmTC_dd5bb.dir\main.cu.obj.d -x cu -c D:\bld\onnxruntime_1716234839539\work\build-ci\Release\CMakeFiles\CMakeScratch\TryCompile-fjxebz\main.cu -o CMakeFiles\cmTC_dd5bb.dir\main.cu.obj -Xcompiler=-FdCMakeFiles\cmTC_dd5bb.dir\,-FS
> ```
> 
> Are the `/DWIN32 /D_WINDOWS /DWINAPI_FAMILY=100 /DWINVER=0x0A00 /D_WIN32_WINNT=0x0A00 /DNTDDI_VERSION=0x0A000000 /DONNXRUNTIME_ENABLE_INTEL_METEOR_LAKE_MOBILE_PLATFORM_PERF_PATCH /DNDEBUG` options, manually converting them to `-DWIN32 -D_WINDOWS -DWINAPI_FAMILY=100 -DWINVER=0x0A00 -D_WIN32_WINNT=0x0A00 -DNTDDI_VERSION=0x0A000000 -DONNXRUNTIME_ENABLE_INTEL_METEOR_LAKE_MOBILE_PLATFORM_PERF_PATCH -DNDEBUG` everything compiles fine (actually, at least the error is different).

As it does not seem to me that `nvcc` supports MSVC-style definitions (i.e. `/DSYMBOL_DEFINED` instead of `-DSYMBOL_DEFINED` ) I added in https://github.com/conda-forge/onnxruntime-feedstock/pull/115/commits/f8f1f9818bfce03ea180a492d7aef2d31bec39cc a simple patch to normalize definitions options in the python build script. I am not sure why this problem does not appear upstream.

**Comment by traversaro** [comment]
> 
> As it does not seem to me that `nvcc` supports MSVC-style definitions (i.e. `/DSYMBOL_DEFINED` instead of `-DSYMBOL_DEFINED` ) I added in [f8f1f98](https://github.com/conda-forge/onnxruntime-feedstock/commit/f8f1f9818bfce03ea180a492d7aef2d31bec39cc) a simple patch to normalize definitions options in the python build script. I am not sure why this problem does not appear upstream.

This fix worked fine. Now the CUDA 12 builds fail (at test level) as it run out of disk space, while CUDA 11 runs out of time. We can switch to `CMAKE_CUDA_ARCHITECTURES=all-major` for CUDA 11, while for CUDA 12 we can check how to get more space in the azure image, or in the worst case we can remove tests.

**Comment by traversaro** [comment]
@conda-forge-admin please rerender

**Comment by traversaro** [comment]
Not sure why, but now all the jobs (even the non-cuda one) are failing with MemoryError while linking `onnxruntime_test_all.exe` :

~~~
[1912/1927] Linking CXX executable onnxruntime_mlas_q4dq.exe
[1913/1927] Building CUDA object CMakeFiles\onnxruntime_shared_lib_test.dir\C_\bld\onnxruntime_1716326872295\work\onnxruntime\test\shared_lib\cuda_ops.cu.obj
Traceback (most recent call last):
  File "C:\Miniforge\Scripts\conda-build-script.py", line 10, in <module>
    return build_tree(
  File "C:\Miniforge\lib\site-packages\conda_build\build.py", line 3638, in build_tree
    packages_from_this = build(
  File "C:\Miniforge\lib\site-packages\conda_build\build.py", line 2462, in build
    windows.build(
  File "C:\Miniforge\lib\site-packages\conda_build\windows.py", line 339, in build
    check_call_env(
  File "C:\Miniforge\lib\site-packages\conda_build\utils.py", line 405, in check_call_env
    return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
  File "C:\Miniforge\lib\site-packages\conda_build\utils.py", line 376, in _func_defaulting_env_to_os_environ
    proc = PopenWrapper(_args, **kwargs)
  File "C:\Miniforge\lib\site-packages\conda_build\utils.py", line 246, in __init__
    self.out, self.err = self._execute(*args, **kwargs)
  File "C:\Miniforge\lib\site-packages\conda_build\utils.py", line 320, in _execute
    self.disk = max(directory_size(disk_usage_dir), self.disk)
  File "C:\Miniforge\lib\site-packages\conda_build\utils.py", line 146, in directory_size
    out = subprocess.check_output(command.format(path), shell=True)
  File "C:\Miniforge\lib\subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Miniforge\lib\subprocess.py", line 505, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "C:\Miniforge\lib\subprocess.py", line 1141, in communicate
    stdout = self.stdout.read()
MemoryError
cuda_ops.cu

tmpxft_000014f0_00000000-10_cuda_ops.compute_90.cudafe1.cpp

[1914/1927] Linking CXX executable onnxruntime_test_all.exe
FAILED: onnxruntime_test_all.exe 
~~~

**Comment by hmaarrfk** [comment]
Maybe we can skip making the test executable….

**Comment by traversaro** [comment]
> Maybe we can skip making the test executable….

Yes, this is exactly what is happening now. I would still like to run tests on non-cuda builds, but that is not a blocker.

**Comment by hmaarrfk** [comment]
> Yes, this is exactly what is happening now.

ah very cool!

**Comment by traversaro** [comment]
Ok, we have a solution working, let me check if I can improve this, but if I fail I will go back to this and cleanup the PR.

**Comment by traversaro** [comment]
Follow up and full matrix test in https://github.com/conda-forge/onnxruntime-feedstock/pull/121 .

**Pull request closed without merging**
