### PR TITLE
Add CMAKE_CUDA_ARCHITECTURES=all to the CMake options

### PR DESCRIPTION
**Pull request by traversaro**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jakirkham** [comment]
Thoughts @conda-forge/onnxruntime ?

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render

**Comment by xhochy** [comment]
Sounds fine 👍 CI issues are because of missing storage space when packaging up the build environment.

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by xhochy** [comment]
CI passed and I think the size increase is reasonable.

**Comment by traversaro** [comment]
> CI passed and I think the size increase is reasonable.

Indeed, `azure:\n  free_disk_space: true` did the trick. @conda-forge/onnxruntime the PR is ready for review.

**Review by xhochy — APPROVED** [review]

**Pull request merged**
